version: '3.3'

services:
  backend:
    image: saveourfavesontario
    build:
      context: ./backend
      dockerfile: Dockerfile
    # command: bash -c "pip install -r requirements.txt && gunicorn -c gunicorn.py carebackend.wsgi"
    command: bash -c "python manage.py runserver 8000"
    ports:
      - "8000:8000"
    env_file:
        - ./.env